setup:
    save_path: "dmd_results"
    save_file: "TrOCR_Esposalles_Koopman_cls_token_out_128_from_ctc_delay_3_new"
    full_grid: False

data:
    dataset:
        Esposalles:
            _target_: main_lkis.EsposallesDatasetForHtr
            dataset_path: "/data/users/cboned/data/HTR/Esposalles"

    collator:
        shuffle: True
        batch_size: 256
        pin_memory: True
        num_workers: 8

models:
    teacher:
        checkpoint_path: "checkpoints/TrOCR_Esposalles.pt"

    student:
        checkpoint_path: "checkpoints/TrOCR_Esposalles_Koopman_cls_token_out_128_ctc_delay_3.pt"
        inputs:
            dim_y: 768
            dim_g_in: 768
            dim_g_out: 128
            delay: 3
