
setup:
    wandb:
        project: Koopman
        group: CLASSIFICATION_LKIS
        name: Test Resnet Trajectories CIFAR100 delay 1 out 3

    dict:
        full_grid: True
        delay: 1
        g_out: 3

data:
    dataset:
        name: cifar100
        dataset_path: "/data/users/cboned/data/Generic/cifar"

    collator:
        shuffle: False
        batch_size: 10
        pin_memory: False
        num_workers: 0

modeling:
    type: resnet
    teacher:
        checkpoint_path: "checkpoints/Resnet_CIFAR100_first_train.pt"

    student:
        checkpoint_path: "checkpoints/Resnet_CIFAR100_Koopman_cls_token_out_3_delay_1.pt"
        finetune: False
        inputs:
            dim_y: 768
            dim_g_in: 768
            dim_g_out: 3
            delay: 1
