log_wandb: False

setup:
    dict:
        jasmin_k: 1
        epochs: 1000
        accumulation_steps: -1
        log_every: 10
        temperature: 4.0
        lambda_param: 0.6
        mse_full_path: False
        use_mse_loss: True
        use_supervision: True
        use_distillation: False
        use_jasmin: True

    wandb:
        project: Koopman
        group: CLASSIFICATION
        name: EDO_DISTILLATION_VIT_ON_CIFAR100_ONE_SAMPLE

data:
    dataset:
        name: "cifar100"
        dataset_path: "/data/users/cboned/cifar"

    collator:
        train:
            shuffle: False
            batch_size: 100
            pin_memory: True
            num_workers: 0
            drop_last: True

modeling:
    type: vit

    teacher:
        checkpoint_path: "checkpoints/Vit_CIFAR100.pt"

    student:
        inputs:
            img_size: 224
            patch_size: 16
            in_chans: 3
            num_classes: 100
            embed_dim: 768
            num_heads: 8
            mlp_ratio: 1
            emulate_depth: 1.0
            time_interval: 1.0
            num_eval_steps: 24
            attn_drop: 0.1
            proj_drop: 0.1
            mlp_drop: 0.1
            l2_attention: False
            add_distillation_token: False
            solver: "euler"

        checkpoint_name: "EDO_DISTILLATION_VIT_ON_CIFAR100_ONE_SAMPLE"

    base:
        checkpoint_path: "checkpoints/Vit_CIFAR100_first_train_reduced.pt"
