log_wandb: False

setup:
    dict:
        epochs: 10
        accumulation_steps: -1
        log_every: 10
        num_hidden_layers: 12
        classifier_only: False

    wandb:
        project: Koopman
        group: CLASSIFICATION
        name: Training_Vit_Imagenet100_DINO_JASMIN

data:
    dataset:
        name: cifar10
        dataset_path: "/data/users/cboned/cifar"

    collator:
        train:
            shuffle: True
            batch_size: 128
            pin_memory: True
            num_workers: 8

        val:
            shuffle: True
            batch_size: 256
            pin_memory: False
            num_workers: 4

        test:
            shuffle: False
            batch_size: 1
            pin_memory: False
            num_workers: 0

modeling:
    type: dino

    checkpoint_name: "Vit_Imagenet100_DINO_JASMIN"
