_wandb:
    value:
        cli_version: 0.19.10
        code_path: code/main_lkis_classification.py
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.10
            "6": 4.51.1
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
delay:
    value: 3
epochs:
    value: 50
full_grid:
    value: true
g_out:
    value: 256
log_every:
    value: 10
num_accumulation_steps:
    value: -1
